### PR TITLE
Issue #39: Fix warnings if user picture does not exist.

### LINKED ISSUE #39: Warning if user has no user picture
In `WopiController::wopiCheckFileInfo()`:

```php
        $user_picture = $user->user_picture->entity;
        if ($user_picture) {
            $avatarUrl = \Drupal::service('file_url_generator')->generateAbsoluteString($user_picture->getFileUri());
        }
[..]
                'avatar' => $avatarUrl,
```

This produces two warning if a user has no user picture:
- Warning: Attempt to read property "entity" on null
- Warning: Undefined variable $avatarUrl

Typically the warnings can be found in the logs after visiting a `/cool/edit/*` page.

### PR DESCRIPTION
**Pull request by donquixote**
Fixes #39

### CODE REVIEW

File: src/Controller/WopiController.php [hunk 1]
```diff
@@ -65,7 +65,7 @@ function wopiCheckFileInfo(string $id, Request $request) {
             'UserId' => $jwt_payload->uid,
             'UserFriendlyName' => $user->getDisplayName(),
             'UserExtraInfo' => [
-                'avatar' => $avatarUrl,
+                'avatar' => $avatarUrl ?? NULL,
```
Comment (hfiguiere) [inline src/Controller/WopiController.php:68]: I think the value `avatar` shouldn't be added if there is no avatar.

Comment (donquixote) [reply src/Controller/WopiController.php:68]: It depends what Collabora expects to find in a request like this.
The proposed change removes the PHP warning, but still sends the same data to Collabora as before.
Sure we can remove the array key if it is NULL, if you say this is ok for Collabora.
